name: Build CI

on:
  - workflow_dispatch
  - push
jobs:
  build_java:
    name: Build Java ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1.4.3
      with:
        java-version: 1.8
    - run: ./gradlew build
    - uses: actions/upload-artifact@v2
      with:
        name: build-java-${{ matrix.os }}
        path: |
          java/build/libs/
          java/build/test-results/test
          java/build/reports/tests/test
  build_csharp:
    name: Build C# ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ 'ubuntu-latest', 'windows-latest' ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: 2.1.607
    - uses: cake-build/cake-action@v1.2.0
      with:
        script-path: csharp/build.cake
    - uses: actions/upload-artifact@v2
      with:
        name: build-csharp-${{ matrix.os }}
        path: csharp/bin/Release/netstandard2.0/
            java/build/reports/tests/test